### ISSUE TITLE
App Crashes When I want to Add Widget

### ISSUE THREAD

**Issue by nasrabadiAM** [01sadra/Detoxiom#3]
Version Code: 1
Version Name: release 2017-12-03-08-27
Environment: LG-H990ds (V20) _ Android 7.0

Description:
Application crash on adding widget to home screen. 
there is no impact on what launcher you're using.

Steps To Reproduce:
1) Install Detoxiom
2) Navigate to the Widgets Screen.
3) Add Detoxiom Widget to Screen.
4) you will see the "Unforunately, Detoxiom has stopped"

Expected result: Detoxiom should be open to show the list of applications”.

This crash happen in in this Activity: https://github.com/01sadra/Detoxiom/blob/master/app/src/main/java/me/sadraa/detoxiom/features/widget/DetoxiomWidgetConfigureActivity.java

logcat error:
```
01-30 13:52:47.418 1935-1935/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: me.sadraa.detoxiom, PID: 1935
                                                 java.lang.OutOfMemoryError: Failed to allocate a 67108876 byte allocation with 21285392 free bytes and 20MB until OOM
                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                     at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
                                                     at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
                                                     at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1152)
                                                     at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:855)
                                                     at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:706)
                                                     at android.content.res.Resources.getDrawable(Resources.java:776)
                                                     at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1040)
                                                     at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:2386)
                                                     at android.app.ApplicationPackageManager.loadItemIcon(ApplicationPackageManager.java:2366)
                                                     at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:223)
                                                     at me.sadraa.detoxiom.features.widget.AppNameAndLogoProvider.getAppLogosArray(Unknown Source)
                                                     at me.sadraa.detoxiom.features.widget.DetoxiomWidgetConfigureActivity.onCreate(Unknown Source)
                                                     at android.app.Activity.performCreate(Activity.java:6754)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6247)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
```

**Comment by nasrabadiAM** [comment]
Storing Apps Drawables To an array may produce this problem.

line 69 of this class:
https://github.com/01sadra/Detoxiom/blob/master/app/src/main/java/me/sadraa/detoxiom/features/widget/AppNameAndLogoProvider.java
